# Generated by Django 2.0.6 on 2018-10-26 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_view_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='view_no',
        ),
    ]
